export default {
  bracketSpacing: true,
  printWidth: 120,
  semi: true,
  singleQuote: true,
  useTabs: false,
  tabWidth: 2,
  trailingComma: 'es5',
  jsxSingleQuote: false,
  bracketSameLine: false,
  arrowParens: 'always',
  importOrder: ['^node:(.*)$', '<THIRD_PARTY_MODULES>', '^~/(.*)$', '^../(.*)$', '^[./]'],
  importOrderParserPlugins: ['importAssertions', 'typescript', 'jsx'],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderGroupNamespaceSpecifiers: true,
  importOrderCaseInsensitive: true,
  singleAttributePerLine: true,
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-ejs'],
};
